---
language: python
python: "2.7"

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - printf '[defaults]\nroles_path = ../' > ansible.cfg


script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo --syntax-check"
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo | grep - 'changed=0.*failed=0'
  && (echo 'Yay! Idempotent!' && exit 0)
  || (echo 'Aaargh, not idempotent' && exit 1)"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
