---

- name: udev rules
  import_tasks: udev.yml

- name: powertop
  import_tasks: powertop.yml

- name: i915
  import_tasks: i915.yml

- name: snd_hda_intel
  import_tasks: snd_hda_intel.yml

- name: tuned
  import_tasks: tuned.yml
